# Generated by Django 3.1.7 on 2021-03-18 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registry_type', models.IntegerField(default=1)),
                ('NIT', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=20)),
                ('partnership_code', models.IntegerField()),
                ('tranmission_date', models.DateField()),
                ('shipping_code', models.CharField(max_length=1)),
                ('expiry_date', models.DateField()),
                ('registry_count', models.IntegerField()),
                ('transactions_total', models.IntegerField()),
                ('details', models.CharField(blank=True, max_length=79)),
            ],
        ),
        migrations.CreateModel(
            name='DetailFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registry_type', models.IntegerField(default=6)),
                ('NIT', models.CharField(blank=True, max_length=13)),
                ('name', models.CharField(blank=True, max_length=20)),
                ('bank_account', models.CharField(blank=True, choices=[(5600078, 'Bancolombia'), (5895142, 'Davivienda'), (1040, 'Banco Agrario'), (5600010, 'Banco de Bogota'), (5600065, 'Itau Corpbanca'), (5600094, 'Citibank'), (5600120, 'Banco Sudameris'), (5600133, 'Banco BBVA'), (5600146, 'Itau'), (5600191, 'Scottia Bank Colpatria'), (5600230, 'Banco de Occidente'), (5600230, 'Banco Caja Social'), (6013677, 'Banco AV Villas'), (1292, 'Confiar'), (1058, 'Banco Procredit Colombia'), (1066, 'Banco Cooperativa Coopcentral'), (1151, 'Rappipay'), (1342, 'Banco Serfinanza'), (1507, 'Nequi'), (1551, 'Daviplata')], max_length=9)),
                ('account_number', models.CharField(blank=True, max_length=17)),
                ('transaction_type', models.CharField(blank=True, choices=[(57, 'Cuenta Corriente'), (67, 'Cuenta de Ahorros'), (77, 'TC Visa'), (87, 'TC Master'), (97, 'Amex')], max_length=2)),
                ('transaction_amount', models.IntegerField()),
                ('validation_indicator', models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=1)),
                ('reference_1', models.CharField(blank=True, max_length=30)),
                ('reference_2', models.CharField(blank=True, max_length=30)),
                ('expiry_date', models.DateField(blank=True)),
                ('billed_period', models.CharField(blank=True, max_length=2)),
                ('cycle', models.CharField(blank=True, max_length=3)),
                ('details', models.CharField(blank=True, max_length=17)),
                ('control_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.controlfile')),
            ],
        ),
    ]
