# Generated by Django 3.1.7 on 2021-03-18 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20210318_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailfile',
            name='control_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_files', to='files.controlfile'),
        ),
    ]
